name: flucoga_server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  json_annotation: ^4.0.1
  shelf_router: ^1.0.0
  http: ^0.13.1
  uuid: ^3.0.4

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^2.0.1
  json_serializable: ^4.1.0

